# 构建阶段
FROM node:18-alpine AS builder
WORKDIR /app

# 复制 package.json 和 package-lock.json
COPY package*.json ./

# 安装依赖
RUN npm install pnpm -g
RUN pnpm install

# 声明构建参数
ARG ENOKI_SECRET_KEY
# 设置环境变量
ENV ENOKI_SECRET_KEY=$ENOKI_SECRET_KEY

# 复制项目文件
COPY . .

# 构建应用
RUN pnpm run build

# 生产阶段
FROM node:18-alpine AS runner
WORKDIR /app

# 设置环境变量为生产环境
ENV NODE_ENV production

# 从构建阶段复制环境变量
ARG ENOKI_SECRET_KEY
ENV ENOKI_SECRET_KEY=$ENOKI_SECRET_KEY

# 复制必要文件
COPY --from=builder /app/next.config.js ./
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

# 暴露端口
EXPOSE 3000

# 启动应用
CMD ["npm", "start"]